### ISSUE TITLE
FixPlrWalkTags named incorrectly

### ISSUE THREAD

**Issue by AJenbo** [nomdenom/devil-beta#2]
https://github.com/nomdenom/devil-beta/blob/d46992ec2fa279959c6e7b6890abc9504f107e19/Source/player.cpp#L1360

**Comment by sskras** [comment]
I didn't get the idea of the comment's content.

**Comment by AJenbo** [comment]
The function called RemovePlrFromMap is actually FixPlrWalkTags, just named incorrectly. The actual RemovePlrFromMap is missing from the beta.

**Comment by nomdenom** [comment]
Fixed :+1:
